/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as protectedRestaurantRouteRouteImport } from './routes/(protected-restaurant)/route'
import { Route as protectedDeliveryRouteRouteImport } from './routes/(protected-delivery)/route'
import { Route as protectedCustomerRouteRouteImport } from './routes/(protected-customer)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as protectedCustomerCheckoutRouteImport } from './routes/(protected-customer)/checkout'
import { Route as protectedCustomerCartRouteImport } from './routes/(protected-customer)/cart'
import { Route as protectedRestaurantDashboardRouteRouteImport } from './routes/(protected-restaurant)/dashboard/route'
import { Route as protectedRestaurantDashboardIndexRouteImport } from './routes/(protected-restaurant)/dashboard/index'
import { Route as protectedDeliveryDeliveriesIndexRouteImport } from './routes/(protected-delivery)/deliveries/index'
import { Route as protectedCustomerRestaurantsIndexRouteImport } from './routes/(protected-customer)/restaurants/index'
import { Route as protectedCustomerProfileIndexRouteImport } from './routes/(protected-customer)/profile/index'
import { Route as protectedCustomerOrdersIndexRouteImport } from './routes/(protected-customer)/orders/index'
import { Route as AuthRegisterUserRouteImport } from './routes/auth/register/user'
import { Route as AuthRegisterRestaurantRouteImport } from './routes/auth/register/restaurant'
import { Route as AuthRegisterDeliveryRouteImport } from './routes/auth/register/delivery'
import { Route as protectedDeliveryDeliveriesDeliveryIdRouteImport } from './routes/(protected-delivery)/deliveries/$deliveryId'
import { Route as protectedCustomerRestaurantsRestaurantIdRouteImport } from './routes/(protected-customer)/restaurants/$restaurantId'
import { Route as protectedCustomerOrdersOrderIdRouteImport } from './routes/(protected-customer)/orders/$orderId'
import { Route as protectedRestaurantDashboardSettingsIndexRouteImport } from './routes/(protected-restaurant)/dashboard/settings/index'
import { Route as protectedRestaurantDashboardOrdersIndexRouteImport } from './routes/(protected-restaurant)/dashboard/orders/index'
import { Route as protectedRestaurantDashboardOpeningHoursIndexRouteImport } from './routes/(protected-restaurant)/dashboard/opening-hours/index'
import { Route as protectedRestaurantDashboardMenuIndexRouteImport } from './routes/(protected-restaurant)/dashboard/menu/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRestaurantRouteRoute =
  protectedRestaurantRouteRouteImport.update({
    id: '/(protected-restaurant)',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedDeliveryRouteRoute = protectedDeliveryRouteRouteImport.update({
  id: '/(protected-delivery)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedCustomerRouteRoute = protectedCustomerRouteRouteImport.update({
  id: '/(protected-customer)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const protectedCustomerCheckoutRoute =
  protectedCustomerCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const protectedCustomerCartRoute = protectedCustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => protectedCustomerRouteRoute,
} as any)
const protectedRestaurantDashboardRouteRoute =
  protectedRestaurantDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedRestaurantRouteRoute,
  } as any)
const protectedRestaurantDashboardIndexRoute =
  protectedRestaurantDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedRestaurantDashboardRouteRoute,
  } as any)
const protectedDeliveryDeliveriesIndexRoute =
  protectedDeliveryDeliveriesIndexRouteImport.update({
    id: '/deliveries/',
    path: '/deliveries/',
    getParentRoute: () => protectedDeliveryRouteRoute,
  } as any)
const protectedCustomerRestaurantsIndexRoute =
  protectedCustomerRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const protectedCustomerProfileIndexRoute =
  protectedCustomerProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const protectedCustomerOrdersIndexRoute =
  protectedCustomerOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const AuthRegisterUserRoute = AuthRegisterUserRouteImport.update({
  id: '/register/user',
  path: '/register/user',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRestaurantRoute = AuthRegisterRestaurantRouteImport.update({
  id: '/register/restaurant',
  path: '/register/restaurant',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterDeliveryRoute = AuthRegisterDeliveryRouteImport.update({
  id: '/register/delivery',
  path: '/register/delivery',
  getParentRoute: () => AuthRouteRoute,
} as any)
const protectedDeliveryDeliveriesDeliveryIdRoute =
  protectedDeliveryDeliveriesDeliveryIdRouteImport.update({
    id: '/deliveries/$deliveryId',
    path: '/deliveries/$deliveryId',
    getParentRoute: () => protectedDeliveryRouteRoute,
  } as any)
const protectedCustomerRestaurantsRestaurantIdRoute =
  protectedCustomerRestaurantsRestaurantIdRouteImport.update({
    id: '/restaurants/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const protectedCustomerOrdersOrderIdRoute =
  protectedCustomerOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const protectedRestaurantDashboardSettingsIndexRoute =
  protectedRestaurantDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => protectedRestaurantDashboardRouteRoute,
  } as any)
const protectedRestaurantDashboardOrdersIndexRoute =
  protectedRestaurantDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => protectedRestaurantDashboardRouteRoute,
  } as any)
const protectedRestaurantDashboardOpeningHoursIndexRoute =
  protectedRestaurantDashboardOpeningHoursIndexRouteImport.update({
    id: '/opening-hours/',
    path: '/opening-hours/',
    getParentRoute: () => protectedRestaurantDashboardRouteRoute,
  } as any)
const protectedRestaurantDashboardMenuIndexRoute =
  protectedRestaurantDashboardMenuIndexRouteImport.update({
    id: '/menu/',
    path: '/menu/',
    getParentRoute: () => protectedRestaurantDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof protectedRestaurantDashboardRouteRouteWithChildren
  '/cart': typeof protectedCustomerCartRoute
  '/checkout': typeof protectedCustomerCheckoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/orders/$orderId': typeof protectedCustomerOrdersOrderIdRoute
  '/restaurants/$restaurantId': typeof protectedCustomerRestaurantsRestaurantIdRoute
  '/deliveries/$deliveryId': typeof protectedDeliveryDeliveriesDeliveryIdRoute
  '/auth/register/delivery': typeof AuthRegisterDeliveryRoute
  '/auth/register/restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/register/user': typeof AuthRegisterUserRoute
  '/orders/': typeof protectedCustomerOrdersIndexRoute
  '/profile/': typeof protectedCustomerProfileIndexRoute
  '/restaurants/': typeof protectedCustomerRestaurantsIndexRoute
  '/deliveries/': typeof protectedDeliveryDeliveriesIndexRoute
  '/dashboard/': typeof protectedRestaurantDashboardIndexRoute
  '/dashboard/menu/': typeof protectedRestaurantDashboardMenuIndexRoute
  '/dashboard/opening-hours/': typeof protectedRestaurantDashboardOpeningHoursIndexRoute
  '/dashboard/orders/': typeof protectedRestaurantDashboardOrdersIndexRoute
  '/dashboard/settings/': typeof protectedRestaurantDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/cart': typeof protectedCustomerCartRoute
  '/checkout': typeof protectedCustomerCheckoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/orders/$orderId': typeof protectedCustomerOrdersOrderIdRoute
  '/restaurants/$restaurantId': typeof protectedCustomerRestaurantsRestaurantIdRoute
  '/deliveries/$deliveryId': typeof protectedDeliveryDeliveriesDeliveryIdRoute
  '/auth/register/delivery': typeof AuthRegisterDeliveryRoute
  '/auth/register/restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/register/user': typeof AuthRegisterUserRoute
  '/orders': typeof protectedCustomerOrdersIndexRoute
  '/profile': typeof protectedCustomerProfileIndexRoute
  '/restaurants': typeof protectedCustomerRestaurantsIndexRoute
  '/deliveries': typeof protectedDeliveryDeliveriesIndexRoute
  '/dashboard': typeof protectedRestaurantDashboardIndexRoute
  '/dashboard/menu': typeof protectedRestaurantDashboardMenuIndexRoute
  '/dashboard/opening-hours': typeof protectedRestaurantDashboardOpeningHoursIndexRoute
  '/dashboard/orders': typeof protectedRestaurantDashboardOrdersIndexRoute
  '/dashboard/settings': typeof protectedRestaurantDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected-customer)': typeof protectedCustomerRouteRouteWithChildren
  '/(protected-delivery)': typeof protectedDeliveryRouteRouteWithChildren
  '/(protected-restaurant)': typeof protectedRestaurantRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(protected-restaurant)/dashboard': typeof protectedRestaurantDashboardRouteRouteWithChildren
  '/(protected-customer)/cart': typeof protectedCustomerCartRoute
  '/(protected-customer)/checkout': typeof protectedCustomerCheckoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/(protected-customer)/orders/$orderId': typeof protectedCustomerOrdersOrderIdRoute
  '/(protected-customer)/restaurants/$restaurantId': typeof protectedCustomerRestaurantsRestaurantIdRoute
  '/(protected-delivery)/deliveries/$deliveryId': typeof protectedDeliveryDeliveriesDeliveryIdRoute
  '/auth/register/delivery': typeof AuthRegisterDeliveryRoute
  '/auth/register/restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/register/user': typeof AuthRegisterUserRoute
  '/(protected-customer)/orders/': typeof protectedCustomerOrdersIndexRoute
  '/(protected-customer)/profile/': typeof protectedCustomerProfileIndexRoute
  '/(protected-customer)/restaurants/': typeof protectedCustomerRestaurantsIndexRoute
  '/(protected-delivery)/deliveries/': typeof protectedDeliveryDeliveriesIndexRoute
  '/(protected-restaurant)/dashboard/': typeof protectedRestaurantDashboardIndexRoute
  '/(protected-restaurant)/dashboard/menu/': typeof protectedRestaurantDashboardMenuIndexRoute
  '/(protected-restaurant)/dashboard/opening-hours/': typeof protectedRestaurantDashboardOpeningHoursIndexRoute
  '/(protected-restaurant)/dashboard/orders/': typeof protectedRestaurantDashboardOrdersIndexRoute
  '/(protected-restaurant)/dashboard/settings/': typeof protectedRestaurantDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/cart'
    | '/checkout'
    | '/auth/login'
    | '/orders/$orderId'
    | '/restaurants/$restaurantId'
    | '/deliveries/$deliveryId'
    | '/auth/register/delivery'
    | '/auth/register/restaurant'
    | '/auth/register/user'
    | '/orders/'
    | '/profile/'
    | '/restaurants/'
    | '/deliveries/'
    | '/dashboard/'
    | '/dashboard/menu/'
    | '/dashboard/opening-hours/'
    | '/dashboard/orders/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/auth/login'
    | '/orders/$orderId'
    | '/restaurants/$restaurantId'
    | '/deliveries/$deliveryId'
    | '/auth/register/delivery'
    | '/auth/register/restaurant'
    | '/auth/register/user'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/deliveries'
    | '/dashboard'
    | '/dashboard/menu'
    | '/dashboard/opening-hours'
    | '/dashboard/orders'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/(protected-customer)'
    | '/(protected-delivery)'
    | '/(protected-restaurant)'
    | '/auth'
    | '/(protected-restaurant)/dashboard'
    | '/(protected-customer)/cart'
    | '/(protected-customer)/checkout'
    | '/auth/login'
    | '/(protected-customer)/orders/$orderId'
    | '/(protected-customer)/restaurants/$restaurantId'
    | '/(protected-delivery)/deliveries/$deliveryId'
    | '/auth/register/delivery'
    | '/auth/register/restaurant'
    | '/auth/register/user'
    | '/(protected-customer)/orders/'
    | '/(protected-customer)/profile/'
    | '/(protected-customer)/restaurants/'
    | '/(protected-delivery)/deliveries/'
    | '/(protected-restaurant)/dashboard/'
    | '/(protected-restaurant)/dashboard/menu/'
    | '/(protected-restaurant)/dashboard/opening-hours/'
    | '/(protected-restaurant)/dashboard/orders/'
    | '/(protected-restaurant)/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedCustomerRouteRoute: typeof protectedCustomerRouteRouteWithChildren
  protectedDeliveryRouteRoute: typeof protectedDeliveryRouteRouteWithChildren
  protectedRestaurantRouteRoute: typeof protectedRestaurantRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected-restaurant)': {
      id: '/(protected-restaurant)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRestaurantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected-delivery)': {
      id: '/(protected-delivery)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedDeliveryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected-customer)': {
      id: '/(protected-customer)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedCustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(protected-customer)/checkout': {
      id: '/(protected-customer)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof protectedCustomerCheckoutRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/(protected-customer)/cart': {
      id: '/(protected-customer)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof protectedCustomerCartRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/(protected-restaurant)/dashboard': {
      id: '/(protected-restaurant)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedRestaurantDashboardRouteRouteImport
      parentRoute: typeof protectedRestaurantRouteRoute
    }
    '/(protected-restaurant)/dashboard/': {
      id: '/(protected-restaurant)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedRestaurantDashboardIndexRouteImport
      parentRoute: typeof protectedRestaurantDashboardRouteRoute
    }
    '/(protected-delivery)/deliveries/': {
      id: '/(protected-delivery)/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof protectedDeliveryDeliveriesIndexRouteImport
      parentRoute: typeof protectedDeliveryRouteRoute
    }
    '/(protected-customer)/restaurants/': {
      id: '/(protected-customer)/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof protectedCustomerRestaurantsIndexRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/(protected-customer)/profile/': {
      id: '/(protected-customer)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedCustomerProfileIndexRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/(protected-customer)/orders/': {
      id: '/(protected-customer)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof protectedCustomerOrdersIndexRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/auth/register/user': {
      id: '/auth/register/user'
      path: '/register/user'
      fullPath: '/auth/register/user'
      preLoaderRoute: typeof AuthRegisterUserRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/restaurant': {
      id: '/auth/register/restaurant'
      path: '/register/restaurant'
      fullPath: '/auth/register/restaurant'
      preLoaderRoute: typeof AuthRegisterRestaurantRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/delivery': {
      id: '/auth/register/delivery'
      path: '/register/delivery'
      fullPath: '/auth/register/delivery'
      preLoaderRoute: typeof AuthRegisterDeliveryRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(protected-delivery)/deliveries/$deliveryId': {
      id: '/(protected-delivery)/deliveries/$deliveryId'
      path: '/deliveries/$deliveryId'
      fullPath: '/deliveries/$deliveryId'
      preLoaderRoute: typeof protectedDeliveryDeliveriesDeliveryIdRouteImport
      parentRoute: typeof protectedDeliveryRouteRoute
    }
    '/(protected-customer)/restaurants/$restaurantId': {
      id: '/(protected-customer)/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId'
      preLoaderRoute: typeof protectedCustomerRestaurantsRestaurantIdRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/(protected-customer)/orders/$orderId': {
      id: '/(protected-customer)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof protectedCustomerOrdersOrderIdRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/(protected-restaurant)/dashboard/settings/': {
      id: '/(protected-restaurant)/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof protectedRestaurantDashboardSettingsIndexRouteImport
      parentRoute: typeof protectedRestaurantDashboardRouteRoute
    }
    '/(protected-restaurant)/dashboard/orders/': {
      id: '/(protected-restaurant)/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof protectedRestaurantDashboardOrdersIndexRouteImport
      parentRoute: typeof protectedRestaurantDashboardRouteRoute
    }
    '/(protected-restaurant)/dashboard/opening-hours/': {
      id: '/(protected-restaurant)/dashboard/opening-hours/'
      path: '/opening-hours'
      fullPath: '/dashboard/opening-hours/'
      preLoaderRoute: typeof protectedRestaurantDashboardOpeningHoursIndexRouteImport
      parentRoute: typeof protectedRestaurantDashboardRouteRoute
    }
    '/(protected-restaurant)/dashboard/menu/': {
      id: '/(protected-restaurant)/dashboard/menu/'
      path: '/menu'
      fullPath: '/dashboard/menu/'
      preLoaderRoute: typeof protectedRestaurantDashboardMenuIndexRouteImport
      parentRoute: typeof protectedRestaurantDashboardRouteRoute
    }
  }
}

interface protectedCustomerRouteRouteChildren {
  protectedCustomerCartRoute: typeof protectedCustomerCartRoute
  protectedCustomerCheckoutRoute: typeof protectedCustomerCheckoutRoute
  protectedCustomerOrdersOrderIdRoute: typeof protectedCustomerOrdersOrderIdRoute
  protectedCustomerRestaurantsRestaurantIdRoute: typeof protectedCustomerRestaurantsRestaurantIdRoute
  protectedCustomerOrdersIndexRoute: typeof protectedCustomerOrdersIndexRoute
  protectedCustomerProfileIndexRoute: typeof protectedCustomerProfileIndexRoute
  protectedCustomerRestaurantsIndexRoute: typeof protectedCustomerRestaurantsIndexRoute
}

const protectedCustomerRouteRouteChildren: protectedCustomerRouteRouteChildren =
  {
    protectedCustomerCartRoute: protectedCustomerCartRoute,
    protectedCustomerCheckoutRoute: protectedCustomerCheckoutRoute,
    protectedCustomerOrdersOrderIdRoute: protectedCustomerOrdersOrderIdRoute,
    protectedCustomerRestaurantsRestaurantIdRoute:
      protectedCustomerRestaurantsRestaurantIdRoute,
    protectedCustomerOrdersIndexRoute: protectedCustomerOrdersIndexRoute,
    protectedCustomerProfileIndexRoute: protectedCustomerProfileIndexRoute,
    protectedCustomerRestaurantsIndexRoute:
      protectedCustomerRestaurantsIndexRoute,
  }

const protectedCustomerRouteRouteWithChildren =
  protectedCustomerRouteRoute._addFileChildren(
    protectedCustomerRouteRouteChildren,
  )

interface protectedDeliveryRouteRouteChildren {
  protectedDeliveryDeliveriesDeliveryIdRoute: typeof protectedDeliveryDeliveriesDeliveryIdRoute
  protectedDeliveryDeliveriesIndexRoute: typeof protectedDeliveryDeliveriesIndexRoute
}

const protectedDeliveryRouteRouteChildren: protectedDeliveryRouteRouteChildren =
  {
    protectedDeliveryDeliveriesDeliveryIdRoute:
      protectedDeliveryDeliveriesDeliveryIdRoute,
    protectedDeliveryDeliveriesIndexRoute:
      protectedDeliveryDeliveriesIndexRoute,
  }

const protectedDeliveryRouteRouteWithChildren =
  protectedDeliveryRouteRoute._addFileChildren(
    protectedDeliveryRouteRouteChildren,
  )

interface protectedRestaurantDashboardRouteRouteChildren {
  protectedRestaurantDashboardIndexRoute: typeof protectedRestaurantDashboardIndexRoute
  protectedRestaurantDashboardMenuIndexRoute: typeof protectedRestaurantDashboardMenuIndexRoute
  protectedRestaurantDashboardOpeningHoursIndexRoute: typeof protectedRestaurantDashboardOpeningHoursIndexRoute
  protectedRestaurantDashboardOrdersIndexRoute: typeof protectedRestaurantDashboardOrdersIndexRoute
  protectedRestaurantDashboardSettingsIndexRoute: typeof protectedRestaurantDashboardSettingsIndexRoute
}

const protectedRestaurantDashboardRouteRouteChildren: protectedRestaurantDashboardRouteRouteChildren =
  {
    protectedRestaurantDashboardIndexRoute:
      protectedRestaurantDashboardIndexRoute,
    protectedRestaurantDashboardMenuIndexRoute:
      protectedRestaurantDashboardMenuIndexRoute,
    protectedRestaurantDashboardOpeningHoursIndexRoute:
      protectedRestaurantDashboardOpeningHoursIndexRoute,
    protectedRestaurantDashboardOrdersIndexRoute:
      protectedRestaurantDashboardOrdersIndexRoute,
    protectedRestaurantDashboardSettingsIndexRoute:
      protectedRestaurantDashboardSettingsIndexRoute,
  }

const protectedRestaurantDashboardRouteRouteWithChildren =
  protectedRestaurantDashboardRouteRoute._addFileChildren(
    protectedRestaurantDashboardRouteRouteChildren,
  )

interface protectedRestaurantRouteRouteChildren {
  protectedRestaurantDashboardRouteRoute: typeof protectedRestaurantDashboardRouteRouteWithChildren
}

const protectedRestaurantRouteRouteChildren: protectedRestaurantRouteRouteChildren =
  {
    protectedRestaurantDashboardRouteRoute:
      protectedRestaurantDashboardRouteRouteWithChildren,
  }

const protectedRestaurantRouteRouteWithChildren =
  protectedRestaurantRouteRoute._addFileChildren(
    protectedRestaurantRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterDeliveryRoute: typeof AuthRegisterDeliveryRoute
  AuthRegisterRestaurantRoute: typeof AuthRegisterRestaurantRoute
  AuthRegisterUserRoute: typeof AuthRegisterUserRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterDeliveryRoute: AuthRegisterDeliveryRoute,
  AuthRegisterRestaurantRoute: AuthRegisterRestaurantRoute,
  AuthRegisterUserRoute: AuthRegisterUserRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedCustomerRouteRoute: protectedCustomerRouteRouteWithChildren,
  protectedDeliveryRouteRoute: protectedDeliveryRouteRouteWithChildren,
  protectedRestaurantRouteRoute: protectedRestaurantRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
