/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as protectedRestaurantRouteRouteImport } from './routes/(protected-restaurant)/route'
import { Route as protectedCustomerRouteRouteImport } from './routes/(protected-customer)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as protectedRestaurantManageRestaurantRouteImport } from './routes/(protected-restaurant)/manage-restaurant'
import { Route as protectedCustomerRestaurantsIndexRouteImport } from './routes/(protected-customer)/restaurants/index'
import { Route as AuthRegisterUserRouteImport } from './routes/auth/register/user'
import { Route as AuthRegisterRestaurantRouteImport } from './routes/auth/register/restaurant'
import { Route as protectedCustomerRestaurantsRestaurantIdRouteImport } from './routes/(protected-customer)/restaurants/$restaurantId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRestaurantRouteRoute =
  protectedRestaurantRouteRouteImport.update({
    id: '/(protected-restaurant)',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedCustomerRouteRoute = protectedCustomerRouteRouteImport.update({
  id: '/(protected-customer)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const protectedRestaurantManageRestaurantRoute =
  protectedRestaurantManageRestaurantRouteImport.update({
    id: '/manage-restaurant',
    path: '/manage-restaurant',
    getParentRoute: () => protectedRestaurantRouteRoute,
  } as any)
const protectedCustomerRestaurantsIndexRoute =
  protectedCustomerRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)
const AuthRegisterUserRoute = AuthRegisterUserRouteImport.update({
  id: '/register/user',
  path: '/register/user',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRestaurantRoute = AuthRegisterRestaurantRouteImport.update({
  id: '/register/restaurant',
  path: '/register/restaurant',
  getParentRoute: () => AuthRouteRoute,
} as any)
const protectedCustomerRestaurantsRestaurantIdRoute =
  protectedCustomerRestaurantsRestaurantIdRouteImport.update({
    id: '/restaurants/$restaurantId',
    path: '/restaurants/$restaurantId',
    getParentRoute: () => protectedCustomerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/manage-restaurant': typeof protectedRestaurantManageRestaurantRoute
  '/auth/login': typeof AuthLoginRoute
  '/restaurants/$restaurantId': typeof protectedCustomerRestaurantsRestaurantIdRoute
  '/auth/register/restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/register/user': typeof AuthRegisterUserRoute
  '/restaurants/': typeof protectedCustomerRestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/manage-restaurant': typeof protectedRestaurantManageRestaurantRoute
  '/auth/login': typeof AuthLoginRoute
  '/restaurants/$restaurantId': typeof protectedCustomerRestaurantsRestaurantIdRoute
  '/auth/register/restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/register/user': typeof AuthRegisterUserRoute
  '/restaurants': typeof protectedCustomerRestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected-customer)': typeof protectedCustomerRouteRouteWithChildren
  '/(protected-restaurant)': typeof protectedRestaurantRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(protected-restaurant)/manage-restaurant': typeof protectedRestaurantManageRestaurantRoute
  '/auth/login': typeof AuthLoginRoute
  '/(protected-customer)/restaurants/$restaurantId': typeof protectedCustomerRestaurantsRestaurantIdRoute
  '/auth/register/restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/register/user': typeof AuthRegisterUserRoute
  '/(protected-customer)/restaurants/': typeof protectedCustomerRestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/manage-restaurant'
    | '/auth/login'
    | '/restaurants/$restaurantId'
    | '/auth/register/restaurant'
    | '/auth/register/user'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/manage-restaurant'
    | '/auth/login'
    | '/restaurants/$restaurantId'
    | '/auth/register/restaurant'
    | '/auth/register/user'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/(protected-customer)'
    | '/(protected-restaurant)'
    | '/auth'
    | '/(protected-restaurant)/manage-restaurant'
    | '/auth/login'
    | '/(protected-customer)/restaurants/$restaurantId'
    | '/auth/register/restaurant'
    | '/auth/register/user'
    | '/(protected-customer)/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedCustomerRouteRoute: typeof protectedCustomerRouteRouteWithChildren
  protectedRestaurantRouteRoute: typeof protectedRestaurantRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected-restaurant)': {
      id: '/(protected-restaurant)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRestaurantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected-customer)': {
      id: '/(protected-customer)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedCustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(protected-restaurant)/manage-restaurant': {
      id: '/(protected-restaurant)/manage-restaurant'
      path: '/manage-restaurant'
      fullPath: '/manage-restaurant'
      preLoaderRoute: typeof protectedRestaurantManageRestaurantRouteImport
      parentRoute: typeof protectedRestaurantRouteRoute
    }
    '/(protected-customer)/restaurants/': {
      id: '/(protected-customer)/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof protectedCustomerRestaurantsIndexRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
    '/auth/register/user': {
      id: '/auth/register/user'
      path: '/register/user'
      fullPath: '/auth/register/user'
      preLoaderRoute: typeof AuthRegisterUserRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/restaurant': {
      id: '/auth/register/restaurant'
      path: '/register/restaurant'
      fullPath: '/auth/register/restaurant'
      preLoaderRoute: typeof AuthRegisterRestaurantRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(protected-customer)/restaurants/$restaurantId': {
      id: '/(protected-customer)/restaurants/$restaurantId'
      path: '/restaurants/$restaurantId'
      fullPath: '/restaurants/$restaurantId'
      preLoaderRoute: typeof protectedCustomerRestaurantsRestaurantIdRouteImport
      parentRoute: typeof protectedCustomerRouteRoute
    }
  }
}

interface protectedCustomerRouteRouteChildren {
  protectedCustomerRestaurantsRestaurantIdRoute: typeof protectedCustomerRestaurantsRestaurantIdRoute
  protectedCustomerRestaurantsIndexRoute: typeof protectedCustomerRestaurantsIndexRoute
}

const protectedCustomerRouteRouteChildren: protectedCustomerRouteRouteChildren =
  {
    protectedCustomerRestaurantsRestaurantIdRoute:
      protectedCustomerRestaurantsRestaurantIdRoute,
    protectedCustomerRestaurantsIndexRoute:
      protectedCustomerRestaurantsIndexRoute,
  }

const protectedCustomerRouteRouteWithChildren =
  protectedCustomerRouteRoute._addFileChildren(
    protectedCustomerRouteRouteChildren,
  )

interface protectedRestaurantRouteRouteChildren {
  protectedRestaurantManageRestaurantRoute: typeof protectedRestaurantManageRestaurantRoute
}

const protectedRestaurantRouteRouteChildren: protectedRestaurantRouteRouteChildren =
  {
    protectedRestaurantManageRestaurantRoute:
      protectedRestaurantManageRestaurantRoute,
  }

const protectedRestaurantRouteRouteWithChildren =
  protectedRestaurantRouteRoute._addFileChildren(
    protectedRestaurantRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRestaurantRoute: typeof AuthRegisterRestaurantRoute
  AuthRegisterUserRoute: typeof AuthRegisterUserRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRestaurantRoute: AuthRegisterRestaurantRoute,
  AuthRegisterUserRoute: AuthRegisterUserRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedCustomerRouteRoute: protectedCustomerRouteRouteWithChildren,
  protectedRestaurantRouteRoute: protectedRestaurantRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
